name: "release"

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile C++ to wasm
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.31
          actions-cache-folder: "emsdk-cache"
      - name: Use pnpm
        run: corepack enable pnpm && pnpm --version
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

